apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-service
  namespace: {{ .Release.Namespace }}
  labels:
        {{- include "template-service.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  progressDeadlineSeconds: 300
  selector:
    matchLabels:
      {{- include "template-service.selectorLabels" . | nindent 6 }} 
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{.Values.maxSurge}}
      maxUnavailable: {{.Values.maxUnavailable}}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "template-service.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}  
      serviceAccountName: {{ include "template-service.serviceAccountName" . }}
      terminationGracePeriodSeconds: 30
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: template-service
        image: {{ include "harnesscommon.names.imagename" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        ports:
          - name: template-grpc
            containerPort: {{ .Values.service.grpcport }}
            protocol: "TCP"
          - name: template-http
            containerPort: {{ .Values.service.port }}
            protocol: "TCP"
          - name: gitsync-grpc
            containerPort: {{ .Values.service.gitsyncgrpcport }}
            protocol: "TCP"
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        env:
          - name: MONGODB_USERNAME
            valueFrom:
              secretKeyRef:
                name: harness-secrets
                key: mongodbUsername
          - name: MONGODB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: harness-secrets
                key: mongodbPassword
          - name : TIMESCALE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: harness-secrets
                key: timescaledbPostgresPassword
          - name: MONGO_URI
            value: 'mongodb://$(MONGODB_USERNAME):$(MONGODB_PASSWORD)@mongodb-replicaset-chart-0.mongodb-replicaset-chart.{{ .Release.Namespace }}.svc:27017/pms-harness?authSource=admin'
        envFrom:
        - configMapRef:
            name: template-service
        readinessProbe:
          httpGet:
            path: /api/health
            port: {{ .Values.service.port }}
          initialDelaySeconds: 60
          timeoutSeconds: 5
          periodSeconds: 5
          failureThreshold: 8
        livenessProbe:
          httpGet:
            path: /api/health
            port: {{ .Values.service.port }}
          initialDelaySeconds: 40
          timeoutSeconds: 5
          periodSeconds: 10
          failureThreshold: 20   
      affinity:   
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - template-service
            topologyKey: "kubernetes.io/hostname"
      {{- with .Values.affinity }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}